#!/usr/bin/env bash

COMMIT="$(git rev-parse --abbrev-ref HEAD)-$(gitver)"
TIMESTAMP=$(date +%FT%T)


build() {
  go get -t -v  ./...
#  go vet ./...
	go build -ldflags "-X main.build=${TIMESTAMP}-${COMMIT}" -o bin/gotrader ./
}

test() {
  build  
  # shellcheck disable=SC2046
  go test -parallel 8 -count=1 -cover $(go list ./... | grep -v /interactivebrokers)
}

test-all() {
  build 
  go test -parallel 8 -count=1 -cover ./...
}

redis-cli() {
  docker run -it --rm --network gotrader_redis redis/redis-stack-server redis-cli -h redis
}

signals-start() {
  docker-compose up 
}