#!/usr/bin/env bash

COMMIT="$(git rev-parse --abbrev-ref HEAD)-$(gitver)"
TIMESTAMP=$(date +%FT%T)

get() {
  go get -t -v  
}

build() {
  get
  go vet
	go build -ldflags "-X main.build=${TIMESTAMP}-${COMMIT}" -o server .
}

test() {
  build
  # shellcheck disable=SC2046
  go test -parallel 8 -count=1 -cover $(go list ./... | grep -v /interactivebrokers)
}

test-all() {
  build 
  go test -parallel 8 -count=1 -cover ./...
}

build-gotaset() {
  go vet
	GOOS=linux go build -ldflags "-X main.build=$(TIMESTAMP)-$(COMMIT)" -o bin/gotaset_linux gotaset/app/main.go
	GOOS=darwin go build -ldflags "-X main.build=$(TIMESTAMP)-$(COMMIT)" -o bin/gotaset_darwin gotaset/app/main.go
}

