name: Build And test
on: [push]
jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Setup shMake
        run: |
          curl -o shmake "https://raw.githubusercontent.com/totomz/shmake/main/shmake"
          chmod +x shmake
      - name: Build 
        run: ./shmake build      
      - name:  Test
        run: ./shmake test      
