name: Build And test
on: [push]
jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Setup shMake
        run: |
          echo "ciao ${PWD}"
          ls -ahl
          curl -o shmake "https://raw.githubusercontent.com/totomz/shmake/main/shmake"
          ls -ahl
      - name: Build And Test
        run: shmake test      
